USE [FACTURADOR01]
GO

/****** Object:  Table [dbo].[ARTICU]    Script Date: 26/04/2019 15:29:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ARTICU](
	[CodArt] [nchar](10) NOT NULL,
	[Descri] [varchar](100) NULL,
	[CodSun] [varchar](8) NOT NULL,
	[GruArt] [int] NOT NULL,
	[PreUni] [money] NULL,
	[LisPre] [int] NULL,
	[CodUni] [varchar](3) NULL,
	[ArtInv] [bit] NULL,
	[ArtCom] [bit] NULL,
	[ArtVen] [bit] NULL,
	[ArtAct] [bit] NULL,
	[ArtIna] [bit] NULL,
 CONSTRAINT [PK_ARTICU] PRIMARY KEY CLUSTERED 
(
	[CodArt] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ARTICU]  WITH CHECK ADD  CONSTRAINT [FK_ARTICU_CODSUN] FOREIGN KEY([CodSun])
REFERENCES [dbo].[CODSUN] ([CodSun])
GO

ALTER TABLE [dbo].[ARTICU] CHECK CONSTRAINT [FK_ARTICU_CODSUN]
GO

ALTER TABLE [dbo].[ARTICU]  WITH CHECK ADD  CONSTRAINT [FK_ARTICU_GRUART] FOREIGN KEY([GruArt])
REFERENCES [dbo].[GRUART] ([CodGru])
GO

ALTER TABLE [dbo].[ARTICU] CHECK CONSTRAINT [FK_ARTICU_GRUART]
GO

ALTER TABLE [dbo].[ARTICU]  WITH CHECK ADD  CONSTRAINT [FK_ARTICU_LISPRE] FOREIGN KEY([LisPre])
REFERENCES [dbo].[LISPRE] ([CodLis])
GO

ALTER TABLE [dbo].[ARTICU] CHECK CONSTRAINT [FK_ARTICU_LISPRE]
GO

ALTER TABLE [dbo].[ARTICU]  WITH CHECK ADD  CONSTRAINT [FK_ARTICU_UNIMED] FOREIGN KEY([CodUni])
REFERENCES [dbo].[UNIMED] ([CodUni])
GO

ALTER TABLE [dbo].[ARTICU] CHECK CONSTRAINT [FK_ARTICU_UNIMED]
GO


