USE [FACTURADOR01]
GO

/****** Object:  Table [dbo].[CODSUN]    Script Date: 26/04/2019 15:29:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CODSUN](
	[CodSun] [varchar](8) NOT NULL,
	[Descri] [varchar](200) NOT NULL,
 CONSTRAINT [PK_CODSUN] PRIMARY KEY CLUSTERED 
(
	[CodSun] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


