USE [FACTURADOR01]
GO

/****** Object:  Table [dbo].[GRUART]    Script Date: 26/04/2019 15:31:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GRUART](
	[CodGru] [int] IDENTITY(1,1) NOT NULL,
	[Descri] [varchar](50) NOT NULL,
 CONSTRAINT [PK_GRUART] PRIMARY KEY CLUSTERED 
(
	[CodGru] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


