USE [FACTURADOR01]
GO

/****** Object:  Table [dbo].[LISPRE]    Script Date: 26/04/2019 15:31:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LISPRE](
	[CodLis] [int] NOT NULL,
	[Descri] [varchar](50) NOT NULL,
	[Ratio] [numeric](18, 4) NOT NULL,
 CONSTRAINT [PK_LISPRE] PRIMARY KEY CLUSTERED 
(
	[CodLis] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


