USE [FACTURADOR01]
GO

/****** Object:  Table [dbo].[UNIMED]    Script Date: 26/04/2019 15:33:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UNIMED](
	[CodUni] [varchar](3) NOT NULL,
	[Descri] [varchar](50) NOT NULL,
 CONSTRAINT [PK_UNIMED] PRIMARY KEY CLUSTERED 
(
	[CodUni] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


